In [2]:
import pandas as pd

In [3]:
import os

In [4]:
csv_path = "C:\\Users\\Admin\\Documents\\Amizhthan\\DC\\dc_characters.csv"

In [7]:
df_csv = pd.read_csv(csv_path)

In [8]:
df_csv

,character_id,real_name,alias,universe,alignment,powers,first_appearance_year
0,1,Clark Kent,Superman,DC,Hero,Super strength; Heat vision; Flight; X-ray vision,1938
1,2,Bruce Wayne,Batman,DC,Hero,Peak human intelligence; Martial arts; Gadgets,1939
2,3,Diana Prince,Wonder Woman,DC,Hero,Super strength; Lasso of Truth; Flight,1941
3,4,Arthur Curry,Aquaman,DC,Hero,Underwater breathing; Telepathy with sea life;...,1941
4,5,Barry Allen,The Flash,DC,Hero,Super speed; Time travel,1956
5,6,Hal Jordan,Green Lantern,DC,Hero,Power ring constructs; Flight; Energy projection,1959
6,7,Victor Stone,Cyborg,DC,Hero,Cybernetic enhancements; Technopathy; Super st...,1980
7,8,Billy Batson,Shazam,DC,Hero,Magic lightning; Super strength; Flight,1940
8,9,Harleen Quinzel,Harley Quinn,DC,Anti-Hero,Agility; Acrobatics; Psychological manipulation,1992
9,10,Unknown,Joker,DC,Villain,Criminal mastermind; Chemical expertise,1940

In [9]:
print("CSV Dataset Shape:", df_csv.shape)
print("\nCSV Columns:", list(df_csv.columns))

CSV Dataset Shape: (10, 7)

CSV Columns: ['character_id', 'real_name', 'alias', 'universe', 'alignment', 'powers', 'first_appearance_year']

In [10]:
print("\n First five rows")
print(df_csv.head())
print("\n Last five rows")
print(df_csv.tail())

 First five rows
   character_id     real_name         alias universe alignment  \
0             1    Clark Kent      Superman       DC      Hero
1             2   Bruce Wayne        Batman       DC      Hero
2             3  Diana Prince  Wonder Woman       DC      Hero
3             4  Arthur Curry       Aquaman       DC      Hero
4             5   Barry Allen     The Flash       DC      Hero

                                              powers  first_appearance_year
0  Super strength; Heat vision; Flight; X-ray vision                   1938
1     Peak human intelligence; Martial arts; Gadgets                   1939
2             Super strength; Lasso of Truth; Flight                   1941
3  Underwater breathing; Telepathy with sea life;...                   1941
4                           Super speed; Time travel                   1956

 Last five rows
   character_id        real_name          alias universe  alignment  \
5             6       Hal Jordan  Green Lantern       DC       Hero
6             7     Victor Stone         Cyborg       DC       Hero
7             8     Billy Batson         Shazam       DC       Hero
8             9  Harleen Quinzel   Harley Quinn       DC  Anti-Hero
9            10          Unknown          Joker       DC    Villain

                                              powers  first_appearance_year
5   Power ring constructs; Flight; Energy projection                   1959
6  Cybernetic enhancements; Technopathy; Super st...                   1980
7            Magic lightning; Super strength; Flight                   1940
8    Agility; Acrobatics; Psychological manipulation                   1992
9            Criminal mastermind; Chemical expertise                   1940

In [11]:
print(df_csv.describe())

       character_id  first_appearance_year
count      10.00000              10.000000
mean        5.50000            1952.600000
std         3.02765              19.265398
min         1.00000            1938.000000
25%         3.25000            1940.000000
50%         5.50000            1941.000000
75%         7.75000            1958.250000
max        10.00000            1992.000000

In [12]:
print("\nData Types:")
print(df_csv.dtypes)

Data Types:
character_id              int64
real_name                object
alias                    object
universe                 object
alignment                object
powers                   object
first_appearance_year     int64
dtype: object

In [13]:
print("\nMissing Values:")
print(df_csv.isnull().sum())

Missing Values:
character_id             0
real_name                0
alias                    0
universe                 0
alignment                0
powers                   0
first_appearance_year    0
dtype: int64

In [14]:
df_csv.columns

Index(['character_id', 'real_name', 'alias', 'universe', 'alignment', 'powers',
       'first_appearance_year'],
      dtype='object')

In [15]:
df_csv.columns.value_counts()

character_id             1
real_name                1
alias                    1
universe                 1
alignment                1
powers                   1
first_appearance_year    1
Name: count, dtype: int64

In [16]:
print("\nBasic Statistics:")
print(df_csv.describe(include="all"))

Basic Statistics:
        character_id   real_name     alias universe alignment  \
count       10.00000          10        10       10        10
unique           NaN          10        10        1         3
top              NaN  Clark Kent  Superman       DC      Hero
freq             NaN           1         1       10         8
mean         5.50000         NaN       NaN      NaN       NaN
std          3.02765         NaN       NaN      NaN       NaN
min          1.00000         NaN       NaN      NaN       NaN
25%          3.25000         NaN       NaN      NaN       NaN
50%          5.50000         NaN       NaN      NaN       NaN
75%          7.75000         NaN       NaN      NaN       NaN
max         10.00000         NaN       NaN      NaN       NaN

                                                   powers  \
count                                                  10
unique                                                 10
top     Super strength; Heat vision; Flight; X-ray vision
freq                                                    1
mean                                                  NaN
std                                                   NaN
min                                                   NaN
25%                                                   NaN
50%                                                   NaN
75%                                                   NaN
max                                                   NaN

        first_appearance_year
count               10.000000
unique                    NaN
top                       NaN
freq                      NaN
mean              1952.600000
std                 19.265398
min               1938.000000
25%               1940.000000
50%               1941.000000
75%               1958.250000
max               1992.000000

In [17]:
import json

In [18]:
import pandas as pd

In [21]:
json_path = "C:\\Users\\Admin\\Documents\\Amizhthan\\DC\\dc_characters.json"

In [22]:
with open(json_path, "r") as f:
    raw_data = json.load(f)

In [23]:
print("Total JSON Records:", len(raw_data))

Total JSON Records: 10

In [24]:
df_json = pd.json_normalize(raw_data)

In [25]:
print("\nFlattend JSON Columns:")
print(df_json.columns)

Flattend JSON Columns:
Index(['character_id', 'real_name', 'alias', 'universe', 'alignment', 'powers',
       'first_appearance_year'],
      dtype='object')

In [26]:
print("\nSample Records:")
print(df_json.head())

Sample Records:
   character_id     real_name         alias universe alignment  \
0             1    Clark Kent      Superman       DC      Hero
1             2   Bruce Wayne        Batman       DC      Hero
2             3  Diana Prince  Wonder Woman       DC      Hero
3             4  Arthur Curry       Aquaman       DC      Hero
4             5   Barry Allen     The Flash       DC      Hero

                                              powers  first_appearance_year
0  [Super strength, Heat vision, Flight, X-ray vi...                   1938
1   [Peak human intelligence, Martial arts, Gadgets]                   1939
2           [Super strength, Lasso of Truth, Flight]                   1941
3  [Underwater breathing, Telepathy with sea life...                   1941
4                         [Super speed, Time travel]                   1956

In [27]:
print("\nSample Records:")
print(df_json.tail())

Sample Records:
   character_id        real_name          alias universe  alignment  \
5             6       Hal Jordan  Green Lantern       DC       Hero
6             7     Victor Stone         Cyborg       DC       Hero
7             8     Billy Batson         Shazam       DC       Hero
8             9  Harleen Quinzel   Harley Quinn       DC  Anti-Hero
9            10          Unknown          Joker       DC    Villain

                                              powers  first_appearance_year
5  [Power ring constructs, Flight, Energy project...                   1959
6  [Cybernetic enhancements, Technopathy, Super s...                   1980
7          [Magic lightning, Super strength, Flight]                   1940
8  [Agility, Acrobatics, Psychological manipulation]                   1992
9          [Criminal mastermind, Chemical expertise]                   1940

In [28]:
import pandas as pd

In [29]:
parquet_path = "C:\\Users\\Admin\\Documents\\Amizhthan\\DC\\dc_characters.parquet"

In [30]:
df_parquet = pd.read_parquet(parquet_path, engine="pyarrow")

In [31]:
print("Parquet Shape:",df_parquet.shape)
print("\nColumns:",df_parquet.columns)

Parquet Shape: (10, 7)

Columns: Index(['character_id', 'real_name', 'alias', 'universe', 'alignment', 'powers',
       'first_appearance_year'],
      dtype='object')

In [32]:
print("\nSample Records:")
print(df_parquet.head())

Sample Records:
   character_id     real_name         alias universe alignment  \
0             1    Clark Kent      Superman       DC      Hero
1             2   Bruce Wayne        Batman       DC      Hero
2             3  Diana Prince  Wonder Woman       DC      Hero
3             4  Arthur Curry       Aquaman       DC      Hero
4             5   Barry Allen     The Flash       DC      Hero

                                              powers  first_appearance_year
0  [Super strength, Heat vision, Flight, X-ray vi...                   1938
1   [Peak human intelligence, Martial arts, Gadgets]                   1939
2           [Super strength, Lasso of Truth, Flight]                   1941
3  [Underwater breathing, Telepathy with sea life...                   1941
4                         [Super speed, Time travel]                   1956

In [33]:
print("\nSample Records:")
print(df_parquet.head(10))

Sample Records:
   character_id        real_name          alias universe  alignment  \
0             1       Clark Kent       Superman       DC       Hero
1             2      Bruce Wayne         Batman       DC       Hero
2             3     Diana Prince   Wonder Woman       DC       Hero
3             4     Arthur Curry        Aquaman       DC       Hero
4             5      Barry Allen      The Flash       DC       Hero
5             6       Hal Jordan  Green Lantern       DC       Hero
6             7     Victor Stone         Cyborg       DC       Hero
7             8     Billy Batson         Shazam       DC       Hero
8             9  Harleen Quinzel   Harley Quinn       DC  Anti-Hero
9            10          Unknown          Joker       DC    Villain

                                              powers  first_appearance_year
0  [Super strength, Heat vision, Flight, X-ray vi...                   1938
1   [Peak human intelligence, Martial arts, Gadgets]                   1939
2           [Super strength, Lasso of Truth, Flight]                   1941
3  [Underwater breathing, Telepathy with sea life...                   1941
4                         [Super speed, Time travel]                   1956
5  [Power ring constructs, Flight, Energy project...                   1959
6  [Cybernetic enhancements, Technopathy, Super s...                   1980
7          [Magic lightning, Super strength, Flight]                   1940
8  [Agility, Acrobatics, Psychological manipulation]                   1992
9          [Criminal mastermind, Chemical expertise]                   1940

In [34]:
print("\nSample Records:")
print(df_parquet.tail())

Sample Records:
   character_id        real_name          alias universe  alignment  \
5             6       Hal Jordan  Green Lantern       DC       Hero
6             7     Victor Stone         Cyborg       DC       Hero
7             8     Billy Batson         Shazam       DC       Hero
8             9  Harleen Quinzel   Harley Quinn       DC  Anti-Hero
9            10          Unknown          Joker       DC    Villain

                                              powers  first_appearance_year
5  [Power ring constructs, Flight, Energy project...                   1959
6  [Cybernetic enhancements, Technopathy, Super s...                   1980
7          [Magic lightning, Super strength, Flight]                   1940
8  [Agility, Acrobatics, Psychological manipulation]                   1992
9          [Criminal mastermind, Chemical expertise]                   1940

In [35]:
print("\nParquet Data Types:")
print(df_parquet.dtypes)

Parquet Data Types:
character_id              int64
real_name                object
alias                    object
universe                 object
alignment                object
powers                   object
first_appearance_year     int64
dtype: object

In [36]:
df_parquet.head()

,character_id,real_name,alias,universe,alignment,powers,first_appearance_year
0,1,Clark Kent,Superman,DC,Hero,"[Super strength, Heat vision, Flight, X-ray vi...",1938
1,2,Bruce Wayne,Batman,DC,Hero,"[Peak human intelligence, Martial arts, Gadgets]",1939
2,3,Diana Prince,Wonder Woman,DC,Hero,"[Super strength, Lasso of Truth, Flight]",1941
3,4,Arthur Curry,Aquaman,DC,Hero,"[Underwater breathing, Telepathy with sea life...",1941
4,5,Barry Allen,The Flash,DC,Hero,"[Super speed, Time travel]",1956

In [37]:
df_parquet.describe()

       character_id  first_appearance_year
count      10.00000              10.000000
mean        5.50000            1952.600000
std         3.02765              19.265398
min         1.00000            1938.000000
25%         3.25000            1940.000000
50%         5.50000            1941.000000
75%         7.75000            1958.250000
max        10.00000            1992.000000